env:
  folder: development-environment

spring:
  cloud:
    config:
      enabled: false

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tracker.io:3308/ems_master
    username: root
    password: live@Bottomhalf_001

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka