env:
  folder: staging-environment

spring:
  config:
    import: optional:configserver:http://configserver-service:8083

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.101:3308/ems_master
    username: root
    password: live@Bottomhalf_001

eureka:
  client:
    enabled: false