server:
  port: 8090

spring:
  application:
    name: apigateway-hiringbell-service
  cloud:
    kubernetes:
      enabled: true
    loadbalancer:
      mode: SERVICE
    discovery:
      all-namespaces: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: coreservice-service
          uri: lb://coreservice-service
          predicates:
            - Path=/hb/api/**
          filters:
            - AuthenticationFilter

  profiles:
    active: ${profile:prod}
